version: "3"

services:
    web:
        build: .
        depends_on: 
            - "database"
        ports:
            - "3000:3000"


    database:
        build: ./database
        ports: 
            - "3306:3306"
        # environment: 
        #     MYSQL_DATABASE: amazon_reviews
        #     MYSQL_USER: root
        #     MYSQL_ROOT_PASSWORD: Skiclub0