version: "3"

services:
    web:
        build:
            context: .
            args: 
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USERNAME}
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        depends_on: 
            - "database"
        ports:
            - "3005:3005"

    database:
        build: 
            context: ./database
            args: 
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports: 
            - "8000:8000"